### ISSUE TITLE
Error to Install.

### ISSUE THREAD

**Issue by rpinto18** [alusev/EGFormValidator#2]
Help me please.
Unable to find a specification for `EGFormValidator`

**Comment by alusev** [comment]
There's an installation guide in the [README](https://github.com/alusev/EGFormValidator/blob/master/README.md).

Can you share an error log or an error message?

**Comment by rpinto18** [comment]
Console... 

<img width="697" alt="capture" src="https://cloud.githubusercontent.com/assets/11068934/23214981/bb0c8548-f8de-11e6-9ad9-182e6119d96d.png">

**Comment by alusev** [comment]
Can you show me your Podfile?

**Comment by rpinto18** [comment]
Yes. 

<img width="627" alt="captura de pantalla 2017-02-22 a las 10 21 29 a m" src="https://cloud.githubusercontent.com/assets/11068934/23217965/e14d4a3a-f8e8-11e6-9abe-15910bdd77d4.png">

**Comment by alusev** [comment]
There's nothing wrong with your configuration file. I couldn't reproduce the error. It's probably has something to do with CocoaPods itself. Can you ```rm -rf ~/.cocoapods/repos/master``` and try installing again?

**Comment by rpinto18** [comment]
I used 'pod update'.  Solved

 Thanks.
